version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: bc-trends
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel, frser-sqlite-datasource, lucasbremond-satellitevisualizer-panel, flaminggoat-maptrack3d-panel
      - BURSTCUBE_DATASOURCE_UID=lmnopqrstuv
      - GF_FEATURE_TOGGLES_ENABLE=nestedFolders
    ports:
      - '3001:3000'
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_storage:/var/lib/grafana
      #- ./grafana-lib:/var/lib/grafana
      #- ./grafana-log:/var/log/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ${BURSTCUBE_DATASOURCE}:/burstcube/burstcube_datasource.db
volumes:
  grafana_storage: {}