version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: burstcube_grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel, frser-sqlite-datasource, lucasbremond-satellitevisualizer-panel, flaminggoat-maptrack3d-panel
    ports:
      - '3001:3000'
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasource/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana-lib:/var/lib/grafana
      - ./grafana-log:/var/log/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
#volumes:
#  grafana_storage: {}