{
 "title": "SC",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ACDS_DA_PKT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RATE_EST_WBN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nRATE_EST_WBN_1,\nRATE_EST_WBN_2,\nRATE_EST_WBN_3\nfrom adcs_ad_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "rawQueryText": "SELECT\nTIME as time, \nRATE_EST_WBN_1,\nRATE_EST_WBN_2,\nRATE_EST_WBN_3\nfrom adcs_ad_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ACDS_DI_PKT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "BVB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nBVB_1,\nBVB_2,\nBVB_3\nfrom adcs_di_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "rawQueryText": "SELECT\nTIME as time, \nBVB_1,\nBVB_2,\nBVB_3\nfrom adcs_di_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "BODY_MOMENTUM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nBODY_MOMENTUM_1,\nBODY_MOMENTUM_2,\nBODY_MOMENTUM_3\nfrom adcs_di_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
       "rawQueryText": "SELECT\nTIME as time, \nBODY_MOMENTUM_1,\nBODY_MOMENTUM_2,\nBODY_MOMENTUM_3\nfrom adcs_di_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "FSS_VALID",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nFSS_VALID_0,\nFSS_VALID_1\nfrom adcs_di_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "rawQueryText": "SELECT\nTIME as time, \nFSS_VALID_0,\nFSS_VALID_1\nfrom adcs_di_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ADCS_GNC_IO_PKT ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SVB",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nSVB_1,\nSVB_2,\nSVB_3\nfrom adcs_gnc_io_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "rawQueryText": "SELECT\nTIME as time, \nSVB_1,\nSVB_2,\nSVB_3\nfrom adcs_gnc_io_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "MODE",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nMODE\nfrom adcs_gnc_io_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "rawQueryText": "SELECT\nTIME as time, \nMODE\nfrom adcs_gnc_io_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CUBIC_CONFIG_PKT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBCR",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nSBCR\nfrom cubic_config_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "rawQueryText": "SELECT\nTIME as time, \nSBCR\nfrom cubic_config_pkt WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  { "title": "GNSS200_ACPKT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "FIX_QUALITY",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nfix_quality\nfrom GNSS200_ACPKT WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
     "rawQueryText": "SELECT\nTIME as time, \nfix_quality\nfrom GNSS200_ACPKT WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "VULCAN_RADIO_HK_TLM_T ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reboot Counter",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nReboot_Counter\nfrom vulcan_radio_hk_tlm_t WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "rawQueryText": "SELECT\nTIME as time, \nReboot_Counter\nfrom vulcan_radio_hk_tlm_t WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "LEO_BUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "STORED_MODE",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nSTORED_MODE\nfrom LEO_BUS_HK_TLM_T  WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "rawQueryText": "SELECT\nTIME as time, \nSTORED_MODE\nfrom LEO_BUS_HK_TLM_T  WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "TRQ_HK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "TRQ_ENABLED",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time, \nTRQ_0_ENABLED,\nTRQ_1_ENABLED,\nTRQ_2_ENABLED\nfrom trq_hk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "rawQueryText": "SELECT\nTIME as time, \nTRQ_0_ENABLED,\nTRQ_1_ENABLED,\nTRQ_2_ENABLED\nfrom trq_hk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}