# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: burstcube-test
    orgId: 1

datasources:
- name: burstcube-ihk
  uid: ${BURSTCUBE_DATASOURCE_UID}
  type: frser-sqlite-datasource
  typeLogoUrl: public/plugins/frser-sqlite-datasource/img/logo.svg
  access: proxy
  url: 
  user:
  database:
  basicAuth: false
  basicAuthUser: ""
  withCredentials: false
  isDefault: true
  jsonData:
    attachLimit: 0
    path: /burstcube/burstcube_datasource.db
    pathPrefix: "file:" 
    secureJsonFields: null
  version: 6
  readonly: false

- name: burstcube-schk
  uid: ${BURSTCUBE_SCHK_DATASOURCE_UID}
  type: frser-sqlite-datasource
  typeLogoUrl: public/plugins/frser-sqlite-datasource/img/logo.svg
  access: proxy
  url: 
  user:
  database:
  basicAuth: false
  basicAuthUser: ""
  withCredentials: false
  isDefault: false
  jsonData:
    attachLimit: 0
    path: /burstcube/burstcube_schk_datasource.db
    pathPrefix: "file:" 
    secureJsonFields: null
  version: 6
  readonly: false  