# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: burstcube-test
    orgId: 1

datasources:
- name: burstcube-test
  type: frser-sqlite-datasource
  typeLogoUrl: public/plugins/frser-sqlite-datasource/img/logo.svg
  access: proxy
  url: 
  user:
  database:
  basicAuth: false
  basicAuthUser: ""
  withCredentials: false
  isDefault: true
  jsonData:
    attachLimit: 0
    path: /burstcube/test102023.db
    pathPrefix: "file:" 
    secureJsonFields: null
  version: 6
  readonly: false