{
 "title": "Instrument Power Things",
 "description": "BurstCube Instrument Reference",
 "time": { "from": "2035-10-16T22:49:46.110Z", "to": "2035-10-17T00:38:28.119Z" },
 "panels": [
  { "title": "Counted Things", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BC_CNDHPHOT_CNT",
   "type": "timeseries",
   "description": "BurstCube C&DH photon coutns",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT TIME, BC_CNDH_0x1B_PHOT_CNT_0, BC_CNDH_0x1C_PHOT_CNT_1, BC_CNDH_0x1D_PHOT_CNT_2, BC_CNDH_0x1E_PHOT_CNT_3 FROM fast_ihk ORDER BY TIME ASC",
     "rawQueryText": "SELECT TIME, BC_CNDH_0x1B_PHOT_CNT_0, BC_CNDH_0x1C_PHOT_CNT_1, BC_CNDH_0x1D_PHOT_CNT_2, BC_CNDH_0x1E_PHOT_CNT_3 FROM fast_ihk ORDER BY TIME ASC",
     "timeColumns": [
      "time",
      "ts",
      "TIME"
     ]
    }
   ]
  },
  {
   "title": "Received Photons (IDATA/TINT)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT TIME as time, \nTINT_IDATA_nphot_recv_DET_0,\nTINT_IDATA_nphot_recv_DET_1,\nTINT_IDATA_nphot_recv_DET_2,\nTINT_IDATA_nphot_recv_DET_3\nFROM fast_ihk ",
     "rawQueryText": "SELECT TIME as time, \nTINT_IDATA_nphot_recv_DET_0,\nTINT_IDATA_nphot_recv_DET_1,\nTINT_IDATA_nphot_recv_DET_2,\nTINT_IDATA_nphot_recv_DET_3\nFROM fast_ihk ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "TTE STORE MISSING THINGS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select TIME as time, TTE_STORE_MISSED_MSGS, TTE_STORE_MISSED_BLOCKS from fast_ihk",
     "rawQueryText": "select TIME as time, TTE_STORE_MISSED_MSGS, TTE_STORE_MISSED_BLOCKS from fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Things about the Detector Heads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Detector Bias",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "select BC_CNDH_0x0_VBIAS_0,\nBC_CNDH_0x1_VBIAS_1,\nBC_CNDH_0x2_VBIAS_2,\nBC_CNDH_0x3_VBIAS_3, TIME as time\n from fast_ihk",
     "rawQueryText": "select BC_CNDH_0x0_VBIAS_0,\nBC_CNDH_0x1_VBIAS_1,\nBC_CNDH_0x2_VBIAS_2,\nBC_CNDH_0x3_VBIAS_3, TIME as time\n from fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "select BC_CNDH_0x4_IBIAS_0,\nBC_CNDH_0x5_IBIAS_1,\nBC_CNDH_0x6_IBIAS_2,\nBC_CNDH_0x7_IBIAS_3, TIME as time\n from fast_ihk",
     "rawQueryText": "select BC_CNDH_0x4_IBIAS_0,\nBC_CNDH_0x5_IBIAS_1,\nBC_CNDH_0x6_IBIAS_2,\nBC_CNDH_0x7_IBIAS_3, TIME as time\n from fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "BIAS RELAY/AMP STATUS",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 7, "x": 9, "y": 20 },
   "targets": [
    {
     "queryText": "select TIME as time, BC_CNDH_0x20_BIAS_RELAY_EN_3,\nBC_CNDH_0x20_BIAS_RELAY_EN_2,\nBC_CNDH_0x20_BIAS_RELAY_EN_1,\nBC_CNDH_0x20_BIAS_RELAY_EN_0,\nBC_CNDH_0x20_IDAB_AMP_EN_3,\nBC_CNDH_0x20_IDAB_AMP_EN_2,\nBC_CNDH_0x20_IDAB_AMP_EN_1,\nBC_CNDH_0x20_IDAB_AMP_EN_0 from fast_ihk",
     "rawQueryText": "select TIME as time, BC_CNDH_0x20_BIAS_RELAY_EN_3,\nBC_CNDH_0x20_BIAS_RELAY_EN_2,\nBC_CNDH_0x20_BIAS_RELAY_EN_1,\nBC_CNDH_0x20_BIAS_RELAY_EN_0,\nBC_CNDH_0x20_IDAB_AMP_EN_3,\nBC_CNDH_0x20_IDAB_AMP_EN_2,\nBC_CNDH_0x20_IDAB_AMP_EN_1,\nBC_CNDH_0x20_IDAB_AMP_EN_0 from fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "IDATA Detector Mask",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "queryText": "select TIME as time, IDATA_DET_3,\nIDATA_DET_2,\nIDATA_DET_1,\nIDATA_DET_0 from fast_ihk",
     "rawQueryText": "select TIME as time, IDATA_DET_3,\nIDATA_DET_2,\nIDATA_DET_1,\nIDATA_DET_0 from fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}