{
 "title": "Datastream Trackers",
 "time": { "from": "2035-10-17T00:09:58.220Z", "to": "2035-10-17T00:38:28.119Z" },
 "panels": [
  { "title": "Event Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IDATA NPHOT RECV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "select \nTIME as time,\nTINT_IDATA_nphot_recv_DET_0 as D0,\nTINT_IDATA_nphot_recv_DET_1 as D1,\nTINT_IDATA_nphot_recv_DET_2 as D2,\nTINT_IDATA_nphot_recv_DET_3 as D3\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "select \nTIME as time,\nTINT_IDATA_nphot_recv_DET_0 as D0,\nTINT_IDATA_nphot_recv_DET_1 as D1,\nTINT_IDATA_nphot_recv_DET_2 as D2,\nTINT_IDATA_nphot_recv_DET_3 as D3\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Integrator IDATA NPHOT RECV",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \nTIME as time,\nTINT_IDATA_nphot_recv_DET_0 as D0,\nTINT_IDATA_nphot_recv_DET_1 as D1,\nTINT_IDATA_nphot_recv_DET_2 as D2,\nTINT_IDATA_nphot_recv_DET_3 as D3\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "select \nTIME as time,\nTINT_IDATA_nphot_recv_DET_0 as D0,\nTINT_IDATA_nphot_recv_DET_1 as D1,\nTINT_IDATA_nphot_recv_DET_2 as D2,\nTINT_IDATA_nphot_recv_DET_3 as D3\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Hit Totals",
   "type": "timeseries",
   "description": "Number of hits received from IDPU and the number of hits counted by the TTE buffer. Should be the same as long as TTE buffer was enabled BEFORE enabling BCSPI. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "select \nTIME as time,\nSPI_BCSPI_R_NPHOTRECV as SPI,\nTTE_R_NPHOTRECV as TTE\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "select \nTIME as time,\nSPI_BCSPI_R_NPHOTRECV as SPI,\nTTE_R_NPHOTRECV as TTE\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Hit Totals",
   "type": "stat",
   "description": "Number of hits received from IDPU and the number of hits counted by the TTE buffer. Should be the same as long as TTE buffer was enabled BEFORE enabling BCSPI. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \nTIME as time,\nSPI_BCSPI_R_NPHOTRECV as SPI,\nTTE_R_NPHOTRECV as TTE\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "select \nTIME as time,\nSPI_BCSPI_R_NPHOTRECV as SPI,\nTTE_R_NPHOTRECV as TTE\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Datastream FIFO Occupancy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Binner FIFO Occupancy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "select TIME as time,\nTINT_CBD_fifo_occupancy as CBD,\nTINT_IDATA_fifo_occupancy as IDATA\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "select TIME as time,\nTINT_CBD_fifo_occupancy as CBD,\nTINT_IDATA_fifo_occupancy as IDATA\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "TTE FIFO Occupancy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "queryText": "select TIME as time,\nTTE_fifo_occupancy as TTE\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "select TIME as time,\nTTE_fifo_occupancy as TTE\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "TTE Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select TIME as time, \nTTE_STORE_MISSED_MSGS as MISSED_MSGS, \nTTE_STORE_MISSED_BLOCKS as MISSED_BLOCKS \nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
     "rawQueryText": "select TIME as time, \nTTE_STORE_MISSED_MSGS as MISSED_MSGS, \nTTE_STORE_MISSED_BLOCKS as MISSED_BLOCKS \nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Indicator",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "queryText": "select TIME as time, \nTTE_STORE_IS_ON\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
     "rawQueryText": "select TIME as time, \nTTE_STORE_IS_ON\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}