{
 "title": "Instrument Reference",
 "time": { "from": "2035-10-16T22:49:46.110Z", "to": "2035-10-17T00:38:28.119Z" },
 "templating": {
  "list": [
   { "name": "detector_id" }
  ]
 },
 "panels": [
  { "title": "Error Flags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OVERCURRENT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x10_OVRCURR_0 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_0 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_0 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_0 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_0 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_0 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_0 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_0 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_0 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_0 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_0 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_0 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_0 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_0 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_0 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_0 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_0 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_0 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_0 AS SDA_LO_VOLT,\n-- BC_CNDH_0x1A_SDA_HI_TEMP_0 AS SDA_HI_TEMP,\n-- BC_CNDH_0x1A_SDA_HI_CURR_0 AS SDA_HI_CURR,\n-- BC_CNDH_0x1A_SDA_HI_VOLT_0 AS SDA_HI_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x10_OVRCURR_0 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_0 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_0 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_0 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_0 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_0 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_0 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_0 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_0 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_0 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_0 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_0 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_0 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_0 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_0 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_0 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_0 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_0 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_0 AS SDA_LO_VOLT,\n-- BC_CNDH_0x1A_SDA_HI_TEMP_0 AS SDA_HI_TEMP,\n-- BC_CNDH_0x1A_SDA_HI_CURR_0 AS SDA_HI_CURR,\n-- BC_CNDH_0x1A_SDA_HI_VOLT_0 AS SDA_HI_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I2C Setup",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x14_I2C_SETUP_TEMP_0 as I2C_SETUP_TEMP,\nBC_CNDH_0x14_I2C_SETUP_CURR_0 as I2C_SETUP_CURR,\nBC_CNDH_0x14_I2C_SETUP_VOLT_0 as I2C_SETUP_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x14_I2C_SETUP_TEMP_0 as I2C_SETUP_TEMP,\nBC_CNDH_0x14_I2C_SETUP_CURR_0 as I2C_SETUP_CURR,\nBC_CNDH_0x14_I2C_SETUP_VOLT_0 as I2C_SETUP_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I2C ADDR NOAK",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_0 AS I2C_ADDR_NOAK_TEMP,\nBC_CNDH_0x15_I2C_ADDR_NOAK_CURR_0 AS I2C_ADDR_NOAK_CURR,\nBC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_0 AS I2C_ADDR_NOAK_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_0 AS I2C_ADDR_NOAK_TEMP,\nBC_CNDH_0x15_I2C_ADDR_NOAK_CURR_0 AS I2C_ADDR_NOAK_CURR,\nBC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_0 AS I2C_ADDR_NOAK_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SCL_LO",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x17_SCL_LO_TEMP_0 AS SCL_LO_TEMP,\nBC_CNDH_0x17_SCL_LO_CURR_0 AS SCL_LO_CURR,\nBC_CNDH_0x17_SCL_LO_VOLT_0 AS SCL_LO_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x17_SCL_LO_TEMP_0 AS SCL_LO_TEMP,\nBC_CNDH_0x17_SCL_LO_CURR_0 AS SCL_LO_CURR,\nBC_CNDH_0x17_SCL_LO_VOLT_0 AS SCL_LO_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SDA_LO",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x19_SDA_LO_TEMP_0 AS SDA_LO_TEMP,\nBC_CNDH_0x19_SDA_LO_CURR_0 AS SDA_LO_CURR,\nBC_CNDH_0x19_SDA_LO_VOLT_0 AS SDA_LO_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x19_SDA_LO_TEMP_0 AS SDA_LO_TEMP,\nBC_CNDH_0x19_SDA_LO_CURR_0 AS SDA_LO_CURR,\nBC_CNDH_0x19_SDA_LO_VOLT_0 AS SDA_LO_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I2C DATA NOAK",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x16_I2C_DATA_NOAK_TEMP_0 AS I2C_DATA_NOAK_TEMP,\nBC_CNDH_0x16_I2C_DATA_NOAK_CURR_0 AS I2C_DATA_NOAK_CURR,\nBC_CNDH_0x16_I2C_DATA_NOAK_VOLT_0 AS I2C_DATA_NOAK_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x16_I2C_DATA_NOAK_TEMP_0 AS I2C_DATA_NOAK_TEMP,\nBC_CNDH_0x16_I2C_DATA_NOAK_CURR_0 AS I2C_DATA_NOAK_CURR,\nBC_CNDH_0x16_I2C_DATA_NOAK_VOLT_0 AS I2C_DATA_NOAK_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SCL_HI",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x18_SCL_HI_TEMP_0 AS SCL_HI_TEMP,\nBC_CNDH_0x18_SCL_HI_CURR_0 AS SCL_HI_CURR,\nBC_CNDH_0x18_SCL_HI_VOLT_0 AS SCL_HI_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x18_SCL_HI_TEMP_0 AS SCL_HI_TEMP,\nBC_CNDH_0x18_SCL_HI_CURR_0 AS SCL_HI_CURR,\nBC_CNDH_0x18_SCL_HI_VOLT_0 AS SCL_HI_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SDA_HI",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\n-- BC_CNDH_0x10_OVRCURR_0 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_0 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_0 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_0 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_0 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_0 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_0 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_0 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_0 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_0 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_0 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_0 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_0 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_0 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_0 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_0 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_0 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_0 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_0 AS SDA_LO_VOLT,\nBC_CNDH_0x1A_SDA_HI_TEMP_0 AS SDA_HI_TEMP,\nBC_CNDH_0x1A_SDA_HI_CURR_0 AS SDA_HI_CURR,\nBC_CNDH_0x1A_SDA_HI_VOLT_0 AS SDA_HI_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\n-- BC_CNDH_0x10_OVRCURR_0 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_0 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_0 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_0 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_0 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_0 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_0 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_0 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_0 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_0 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_0 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_0 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_0 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_0 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_0 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_0 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_0 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_0 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_0 AS SDA_LO_VOLT,\nBC_CNDH_0x1A_SDA_HI_TEMP_0 AS SDA_HI_TEMP,\nBC_CNDH_0x1A_SDA_HI_CURR_0 AS SDA_HI_CURR,\nBC_CNDH_0x1A_SDA_HI_VOLT_0 AS SDA_HI_VOLT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Operational Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Detector 0 SITREP",
   "type": "stat",
   "gridPos": { "h": 13, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_0 as AMP_EN, \n(BC_CNDH_0x10_BIAS_INHIBIT_0 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x10_RELAY_0 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_0) as RELAY_EN,\n(BC_CNDH_0x10_BPSU_0 + 20) as BPSU\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_0 as AMP_EN, \n(BC_CNDH_0x10_BIAS_INHIBIT_0 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x10_RELAY_0 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_0) as RELAY_EN,\n(BC_CNDH_0x10_BPSU_0 + 20) as BPSU\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current, Temperature, Voltage Configuration",
   "type": "stat",
   "description": "Status of override and select flags.",
   "gridPos": { "h": 13, "w": 4, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_OCURR_CTOF_ORIDE_0 + 30 as OCURR_CTOFF_ORIDE,\nBC_CNDH_0x20_OCURR_CTOF_EN_0 as OCURR_CTOFF_EN,\nBC_CNDH_0x25_TEMP_ERR_OVRD_0 + 30 as TEMP_ERR_OVRD, \nBC_CNDH_0x25_VOLT_ERR_OVRD_0 + 30 as VOLT_ERR_OVERD,\nBC_CNDH_0x25_TEMP_AVE_SEL_0 as TEMP_AVE_SEL,\nBC_CNDH_0x25_VOLT_AVE_SEL_0 as VOLT_AGE_SEL\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_OCURR_CTOF_ORIDE_0 + 30 as OCURR_CTOFF_ORIDE,\nBC_CNDH_0x20_OCURR_CTOF_EN_0 as OCURR_CTOFF_EN,\nBC_CNDH_0x25_TEMP_ERR_OVRD_0 + 30 as TEMP_ERR_OVRD, \nBC_CNDH_0x25_VOLT_ERR_OVRD_0 + 30 as VOLT_ERR_OVERD,\nBC_CNDH_0x25_TEMP_AVE_SEL_0 as TEMP_AVE_SEL,\nBC_CNDH_0x25_VOLT_AVE_SEL_0 as VOLT_AGE_SEL\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Detector Snapshot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as D0_VBIAS\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as D0_VBIAS\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Detector Snapshot Trend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as D0_VBIAS\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as D0_VBIAS\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1) as D0_IBIAS\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1) as D0_IBIAS\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1) as D0_IBIAS\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1) as D0_IBIAS\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as D0_TEMP\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as D0_TEMP\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as D0_TEMP\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as D0_TEMP\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as D0_PHOT_CNT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as D0_PHOT_CNT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as D0_PHOT_CNT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as D0_PHOT_CNT\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Settings and Detector Masks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Bias & Threshold Settings",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time\n-- BC_CNDH_0x10_BASEMEDIAN_0,\n-- BC_CNDH_0x28_IBIAS_LIM_0, \n-- BC_CNDH_0x3B_BASE_SELECT_0,\n-- BC_CNDH_0x3B_CONST_BASELN_0,\n-- BC_CNDH_0x42_PULS_LOWPASS_0,\n-- BC_CNDH_0x43_PHA_WIN_0,\n-- BC_CNDH_0x48_PEAK_THRSH\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time\n-- BC_CNDH_0x10_BASEMEDIAN_0,\n-- BC_CNDH_0x28_IBIAS_LIM_0, \n-- BC_CNDH_0x3B_BASE_SELECT_0,\n-- BC_CNDH_0x3B_CONST_BASELN_0,\n-- BC_CNDH_0x42_PULS_LOWPASS_0,\n-- BC_CNDH_0x43_PHA_WIN_0,\n-- BC_CNDH_0x48_PEAK_THRSH\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Datastream Enable Mask",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nCBD_DET_0 as CBD_ENA,\nIDATA_DET_0 as IDATA_ENA\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nCBD_DET_0 as CBD_ENA,\nIDATA_DET_0 as IDATA_ENA\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Datastream Enable Mask Trend",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nCBD_DET_0 as CBD_ENA,\nIDATA_DET_0 as IDATA_ENA\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "rawQueryText": "SELECT\nTIME as time,\nCBD_DET_0 as CBD_ENA,\nIDATA_DET_0 as IDATA_ENA\nfrom fast_ihk WHERE time BETWEEN (${__from:date:seconds}-86400) AND (${__to:date:seconds}+86400)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}