{
 "title": "Detector 1 Operational Status Trends",
 "time": { "from": "2035-10-16T22:49:48.630Z", "to": "2035-10-17T01:20:04.997Z" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 }, "options": { "content": "# Detector 1\n\n" } },
  { "title": "Error Flags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "OVERCURRENT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x11_OVRCURR_1 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT,\n-- BC_CNDH_0x1A_SDA_HI_TEMP_1 AS SDA_HI_TEMP,\n-- BC_CNDH_0x1A_SDA_HI_CURR_1 AS SDA_HI_CURR,\n-- BC_CNDH_0x1A_SDA_HI_VOLT_1 AS SDA_HI_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x11_OVRCURR_1 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT,\n-- BC_CNDH_0x1A_SDA_HI_TEMP_1 AS SDA_HI_TEMP,\n-- BC_CNDH_0x1A_SDA_HI_CURR_1 AS SDA_HI_CURR,\n-- BC_CNDH_0x1A_SDA_HI_VOLT_1 AS SDA_HI_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "OVERCURRENT",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 3 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x11_OVRCURR_1 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT,\n-- BC_CNDH_0x1A_SDA_HI_TEMP_1 AS SDA_HI_TEMP,\n-- BC_CNDH_0x1A_SDA_HI_CURR_1 AS SDA_HI_CURR,\n-- BC_CNDH_0x1A_SDA_HI_VOLT_1 AS SDA_HI_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x11_OVRCURR_1 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT,\n-- BC_CNDH_0x1A_SDA_HI_TEMP_1 AS SDA_HI_TEMP,\n-- BC_CNDH_0x1A_SDA_HI_CURR_1 AS SDA_HI_CURR,\n-- BC_CNDH_0x1A_SDA_HI_VOLT_1 AS SDA_HI_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SCL_LO",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\nBC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\nBC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\nBC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\nBC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SCL_LO",
   "type": "state-timeline",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 3 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\nBC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\nBC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\nBC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\nBC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I2C Setup",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\nBC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\nBC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\nBC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\nBC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I2C Setup",
   "type": "state-timeline",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 7 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\nBC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\nBC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\nBC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\nBC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SCL_HI",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\nBC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\nBC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\nBC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\nBC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SCL_HI",
   "type": "state-timeline",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 7 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\nBC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\nBC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\nBC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\nBC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I2C ADDR NOAK",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\nBC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\nBC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\nBC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\nBC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I2C ADDR NOAK",
   "type": "state-timeline",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\nBC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\nBC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\nBC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\nBC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SDA_LO",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\nBC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\nBC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\nBC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\nBC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SDA_LO",
   "type": "state-timeline",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\nBC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\nBC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\nBC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\nBC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I2C DATA NOAK",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\nBC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\nBC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\nBC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\nBC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "I2C DATA NOAK",
   "type": "state-timeline",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 15 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\nBC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\nBC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\nBC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\nBC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SDA_HI",
   "type": "stat",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\n-- BC_CNDH_0x10_OVRCURR_1 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT,\nBC_CNDH_0x1A_SDA_HI_TEMP_1 AS SDA_HI_TEMP,\nBC_CNDH_0x1A_SDA_HI_CURR_1 AS SDA_HI_CURR,\nBC_CNDH_0x1A_SDA_HI_VOLT_1 AS SDA_HI_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\n-- BC_CNDH_0x10_OVRCURR_1 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT,\nBC_CNDH_0x1A_SDA_HI_TEMP_1 AS SDA_HI_TEMP,\nBC_CNDH_0x1A_SDA_HI_CURR_1 AS SDA_HI_CURR,\nBC_CNDH_0x1A_SDA_HI_VOLT_1 AS SDA_HI_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SDA_HI",
   "type": "state-timeline",
   "description": "TEMP / CURR / VOLT",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 15 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\n-- BC_CNDH_0x10_OVRCURR_1 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT,\nBC_CNDH_0x1A_SDA_HI_TEMP_1 AS SDA_HI_TEMP,\nBC_CNDH_0x1A_SDA_HI_CURR_1 AS SDA_HI_CURR,\nBC_CNDH_0x1A_SDA_HI_VOLT_1 AS SDA_HI_VOLT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\n-- BC_CNDH_0x10_OVRCURR_1 as OVERCURR\n-- BC_CNDH_0x14_I2C_SETUP_TEMP_1 as I2C_SETUP_TEMP,\n-- BC_CNDH_0x14_I2C_SETUP_CURR_1 as I2C_SETUP_CURR,\n-- BC_CNDH_0x14_I2C_SETUP_VOLT_1 as I2C_SETUP_VOLT\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_TEMP_1 AS I2C_ADDR_NOAK_TEMP,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_CURR_1 AS I2C_ADDR_NOAK_CURR,\n-- BC_CNDH_0x15_I2C_ADDR_NOAK_VOLT_1 AS I2C_ADDR_NOAK_VOLT,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_TEMP_1 AS I2C_DATA_NOAK_TEMP,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_CURR_1 AS I2C_DATA_NOAK_CURR,\n-- BC_CNDH_0x16_I2C_DATA_NOAK_VOLT_1 AS I2C_DATA_NOAK_VOLT,\n-- BC_CNDH_0x17_SCL_LO_TEMP_1 AS SCL_LO_TEMP,\n-- BC_CNDH_0x17_SCL_LO_CURR_1 AS SCL_LO_CURR,\n-- BC_CNDH_0x17_SCL_LO_VOLT_1 AS SCL_LO_VOLT,\n-- BC_CNDH_0x18_SCL_HI_TEMP_1 AS SCL_HI_TEMP,\n-- BC_CNDH_0x18_SCL_HI_CURR_1 AS SCL_HI_CURR,\n-- BC_CNDH_0x18_SCL_HI_VOLT_1 AS SCL_HI_VOLT,\n-- BC_CNDH_0x19_SDA_LO_TEMP_1 AS SDA_LO_TEMP,\n-- BC_CNDH_0x19_SDA_LO_CURR_1 AS SDA_LO_CURR,\n-- BC_CNDH_0x19_SDA_LO_VOLT_1 AS SDA_LO_VOLT,\nBC_CNDH_0x1A_SDA_HI_TEMP_1 AS SDA_HI_TEMP,\nBC_CNDH_0x1A_SDA_HI_CURR_1 AS SDA_HI_CURR,\nBC_CNDH_0x1A_SDA_HI_VOLT_1 AS SDA_HI_VOLT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Operational Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Detector Snapshot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x1_VBIAS_1 as VBIAS\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x1_VBIAS_1 as VBIAS\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Detector Trend",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x1_VBIAS_1 as VBIAS\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x1_VBIAS_1 as VBIAS\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "D0",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_1 as AMP_EN, \n(BC_CNDH_0x11_BIAS_INHIBIT_1 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x11_RELAY_1 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_1) as RELAY_EN,\n(BC_CNDH_0x11_BPSU_1 + 20) as BPSU\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_1 as AMP_EN, \n(BC_CNDH_0x11_BIAS_INHIBIT_1 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x11_RELAY_1 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_1) as RELAY_EN,\n(BC_CNDH_0x11_BPSU_1 + 20) as BPSU\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SITREP",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 7, "x": 13, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_1 as AMP_EN, \n(BC_CNDH_0x11_BIAS_INHIBIT_1 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x11_RELAY_1 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_1) as RELAY_EN,\n(BC_CNDH_0x11_BPSU_1 + 20) as BPSU\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_1 as AMP_EN, \n(BC_CNDH_0x11_BIAS_INHIBIT_1 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x11_RELAY_1 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_1) as RELAY_EN,\n(BC_CNDH_0x11_BPSU_1 + 20) as BPSU\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x9_TEMP_1 as TEMP\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x9_TEMP_1 as TEMP\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x9_TEMP_1 as TEMP\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x9_TEMP_1 as TEMP\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current, Temperature, Voltage Configuration",
   "type": "stat",
   "description": "Status of override and select flags.",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_OCURR_CTOF_ORIDE_1 + 30 as OCURR_CTOFF_ORIDE,\nBC_CNDH_0x20_OCURR_CTOF_EN_1 as OCURR_CTOFF_EN,\nBC_CNDH_0x25_TEMP_ERR_OVRD_1 + 30 as TEMP_ERR_OVRD, \nBC_CNDH_0x25_VOLT_ERR_OVRD_1 + 30 as VOLT_ERR_OVERD,\nBC_CNDH_0x25_TEMP_AVE_SEL_1 as TEMP_AVE_SEL,\nBC_CNDH_0x25_VOLT_AVE_SEL_1 as VOLT_AGE_SEL\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_OCURR_CTOF_ORIDE_1 + 30 as OCURR_CTOFF_ORIDE,\nBC_CNDH_0x20_OCURR_CTOF_EN_1 as OCURR_CTOFF_EN,\nBC_CNDH_0x25_TEMP_ERR_OVRD_1 + 30 as TEMP_ERR_OVRD, \nBC_CNDH_0x25_VOLT_ERR_OVRD_1 + 30 as VOLT_ERR_OVERD,\nBC_CNDH_0x25_TEMP_AVE_SEL_1 as TEMP_AVE_SEL,\nBC_CNDH_0x25_VOLT_AVE_SEL_1 as VOLT_AGE_SEL\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current, Temperature, Voltage Configuration",
   "type": "state-timeline",
   "description": "Status of override and select flags.",
   "gridPos": { "h": 12, "w": 7, "x": 4, "y": 33 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_OCURR_CTOF_ORIDE_1 + 30 as OCURR_CTOFF_ORIDE,\nBC_CNDH_0x20_OCURR_CTOF_EN_1 as OCURR_CTOFF_EN,\nBC_CNDH_0x25_TEMP_ERR_OVRD_1 + 30 as TEMP_ERR_OVRD, \nBC_CNDH_0x25_VOLT_ERR_OVRD_1 + 30 as VOLT_ERR_OVERD,\nBC_CNDH_0x25_TEMP_AVE_SEL_1 as TEMP_AVE_SEL,\nBC_CNDH_0x25_VOLT_AVE_SEL_1 as VOLT_AGE_SEL\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_OCURR_CTOF_ORIDE_1 + 30 as OCURR_CTOFF_ORIDE,\nBC_CNDH_0x20_OCURR_CTOF_EN_1 as OCURR_CTOFF_EN,\nBC_CNDH_0x25_TEMP_ERR_OVRD_1 + 30 as TEMP_ERR_OVRD, \nBC_CNDH_0x25_VOLT_ERR_OVRD_1 + 30 as VOLT_ERR_OVERD,\nBC_CNDH_0x25_TEMP_AVE_SEL_1 as TEMP_AVE_SEL,\nBC_CNDH_0x25_VOLT_AVE_SEL_1 as VOLT_AGE_SEL\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Datastream Enable Mask",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nCBD_DET_1 as CBD_ENA,\nIDATA_DET_1 as IDATA_ENA\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nCBD_DET_1 as CBD_ENA,\nIDATA_DET_1 as IDATA_ENA\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Datastream Enable Mask Trend",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 7, "x": 13, "y": 33 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nCBD_DET_1 as CBD_ENA,\nIDATA_DET_1 as IDATA_ENA\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nCBD_DET_1 as CBD_ENA,\nIDATA_DET_1 as IDATA_ENA\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Settings and Detector Masks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Bias & Threshold Settings",
   "type": "stat",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time\n-- BC_CNDH_0x10_BASEMEDIAN_1,\n-- BC_CNDH_0x28_IBIAS_LIM_1, \n-- BC_CNDH_0x3B_BASE_SELECT_1,\n-- BC_CNDH_0x3B_CONST_BASELN_1,\n-- BC_CNDH_0x42_PULS_LOWPASS_1,\n-- BC_CNDH_0x43_PHA_WIN_1,\n-- BC_CNDH_0x48_PEAK_THRSH\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time\n-- BC_CNDH_0x10_BASEMEDIAN_1,\n-- BC_CNDH_0x28_IBIAS_LIM_1, \n-- BC_CNDH_0x3B_BASE_SELECT_1,\n-- BC_CNDH_0x3B_CONST_BASELN_1,\n-- BC_CNDH_0x42_PULS_LOWPASS_1,\n-- BC_CNDH_0x43_PHA_WIN_1,\n-- BC_CNDH_0x48_PEAK_THRSH\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}