{
 "title": "All Detector Reference",
 "time": { "from": "2035-10-16T23:45:32.053Z", "to": "2035-10-17T00:44:15.957Z" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 }, "options": { "content": "# All Detector Snapshot\n\n" } },
  {
   "title": "Detector Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "D0",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_0 as AMP_EN, \n(BC_CNDH_0x10_BIAS_INHIBIT_0 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x10_RELAY_0 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_0) as RELAY_EN,\n(BC_CNDH_0x10_BPSU_0 + 20) as BPSU\nfrom fast_ihk",
       "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_0 as AMP_EN, \n(BC_CNDH_0x10_BIAS_INHIBIT_0 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x10_RELAY_0 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_0) as RELAY_EN,\n(BC_CNDH_0x10_BPSU_0 + 20) as BPSU\nfrom fast_ihk",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "SITREP",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 7, "x": 3, "y": 33 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_0 as AMP_EN, \n(BC_CNDH_0x10_BIAS_INHIBIT_0 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x10_RELAY_0 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_0) as RELAY_EN,\n(BC_CNDH_0x10_BPSU_0 + 20) as BPSU\nfrom fast_ihk",
       "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_0 as AMP_EN, \n(BC_CNDH_0x10_BIAS_INHIBIT_0 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x10_RELAY_0 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_0) as RELAY_EN,\n(BC_CNDH_0x10_BPSU_0 + 20) as BPSU\nfrom fast_ihk",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "D1",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 10, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_1 as AMP_EN, \n(BC_CNDH_0x11_BIAS_INHIBIT_1 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x11_RELAY_1 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_1) as RELAY_EN,\n(BC_CNDH_0x11_BPSU_1 + 20) as BPSU\nfrom fast_ihk",
       "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_1 as AMP_EN, \n(BC_CNDH_0x11_BIAS_INHIBIT_1 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x11_RELAY_1 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_1) as RELAY_EN,\n(BC_CNDH_0x11_BPSU_1 + 20) as BPSU\nfrom fast_ihk",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "SITREP",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 7, "x": 13, "y": 33 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_1 as AMP_EN, \n(BC_CNDH_0x11_BIAS_INHIBIT_1 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x11_RELAY_1 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_1) as RELAY_EN,\n(BC_CNDH_0x11_BPSU_1 + 20) as BPSU\nfrom fast_ihk",
       "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_1 as AMP_EN, \n(BC_CNDH_0x11_BIAS_INHIBIT_1 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x11_RELAY_1 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_1) as RELAY_EN,\n(BC_CNDH_0x11_BPSU_1 + 20) as BPSU\nfrom fast_ihk",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "D2",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_2 as AMP_EN, \n(BC_CNDH_0x12_BIAS_INHIBIT_2 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x12_RELAY_2 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_2) as RELAY_EN,\n(BC_CNDH_0x12_BPSU_2 + 20) as BPSU\nfrom fast_ihk",
       "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_2 as AMP_EN, \n(BC_CNDH_0x12_BIAS_INHIBIT_2 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x12_RELAY_2 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_2) as RELAY_EN,\n(BC_CNDH_0x12_BPSU_2 + 20) as BPSU\nfrom fast_ihk",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "SITREP",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 40 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_2 as AMP_EN, \n(BC_CNDH_0x12_BIAS_INHIBIT_2 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x12_RELAY_2 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_2) as RELAY_EN,\n(BC_CNDH_0x12_BPSU_2 + 20) as BPSU\nfrom fast_ihk",
       "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_2 as AMP_EN, \n(BC_CNDH_0x12_BIAS_INHIBIT_2 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x12_RELAY_2 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_2) as RELAY_EN,\n(BC_CNDH_0x12_BPSU_2 + 20) as BPSU\nfrom fast_ihk",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "D3",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 10, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_3 as AMP_EN, \n(BC_CNDH_0x13_BIAS_INHIBIT_3 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x13_RELAY_3 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_3) as RELAY_EN,\n(BC_CNDH_0x13_BPSU_3 + 20) as BPSU\nfrom fast_ihk",
       "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_3 as AMP_EN, \n(BC_CNDH_0x13_BIAS_INHIBIT_3 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x13_RELAY_3 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_3) as RELAY_EN,\n(BC_CNDH_0x13_BPSU_3 + 20) as BPSU\nfrom fast_ihk",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "SITREP",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 7, "x": 13, "y": 40 },
     "targets": [
      {
       "queryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_3 as AMP_EN, \n(BC_CNDH_0x13_BIAS_INHIBIT_3 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x13_RELAY_3 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_3) as RELAY_EN,\n(BC_CNDH_0x13_BPSU_3 + 20) as BPSU\nfrom fast_ihk",
       "rawQueryText": "SELECT\nTIME as time,\nBC_CNDH_0x20_IDAB_AMP_EN_3 as AMP_EN, \n(BC_CNDH_0x13_BIAS_INHIBIT_3 + 10) as BIAS_INHIBIT, \n(BC_CNDH_0x13_RELAY_3 + 20) as RELAY,\n(BC_CNDH_0x20_BIAS_RELAY_EN_3) as RELAY_EN,\n(BC_CNDH_0x13_BPSU_3 + 20) as BPSU\nfrom fast_ihk",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  { "title": "Operational Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as VBIAS_0,\nBC_CNDH_0x1_VBIAS_1 as VBIAS_1,\nBC_CNDH_0x3_VBIAS_3 as VBIAS_3,\nBC_CNDH_0x2_VBIAS_2 as VBIAS_2\n\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as VBIAS_0,\nBC_CNDH_0x1_VBIAS_1 as VBIAS_1,\nBC_CNDH_0x3_VBIAS_3 as VBIAS_3,\nBC_CNDH_0x2_VBIAS_2 as VBIAS_2\n\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as VBIAS_0,\nBC_CNDH_0x1_VBIAS_1 as VBIAS_1,\nBC_CNDH_0x2_VBIAS_2 as VBIAS_2,\nBC_CNDH_0x3_VBIAS_3 as VBIAS_3\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as VBIAS_0,\nBC_CNDH_0x1_VBIAS_1 as VBIAS_1,\nBC_CNDH_0x2_VBIAS_2 as VBIAS_2,\nBC_CNDH_0x3_VBIAS_3 as VBIAS_3\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as TEMP_0,\nBC_CNDH_0x9_TEMP_1 as TEMP_1,\nBC_CNDH_0xB_TEMP_3 as TEMP_3,\nBC_CNDH_0xA_TEMP_2 as TEMP_2\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as TEMP_0,\nBC_CNDH_0x9_TEMP_1 as TEMP_1,\nBC_CNDH_0xB_TEMP_3 as TEMP_3,\nBC_CNDH_0xA_TEMP_2 as TEMP_2\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as TEMP_0,\nBC_CNDH_0x9_TEMP_1 as TEMP_1,\nBC_CNDH_0xA_TEMP_2 as TEMP_2,\nBC_CNDH_0xB_TEMP_3 as TEMP_3\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as TEMP_0,\nBC_CNDH_0x9_TEMP_1 as TEMP_1,\nBC_CNDH_0xA_TEMP_2 as TEMP_2,\nBC_CNDH_0xB_TEMP_3 as TEMP_3\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0xC_TEMP_IDPU_0 as TEMP_IDPU\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0xC_TEMP_IDPU_0 as TEMP_IDPU\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0xC_TEMP_IDPU_0 as TEMP_IDPU\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0xC_TEMP_IDPU_0 as TEMP_IDPU\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as VBIAS_0,\nBC_CNDH_0x1_VBIAS_1 as VBIAS_1,\nBC_CNDH_0x2_VBIAS_2 as VBIAS_2,\nBC_CNDH_0x3_VBIAS_3 as VBIAS_3\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x0_VBIAS_0 as VBIAS_0,\nBC_CNDH_0x1_VBIAS_1 as VBIAS_1,\nBC_CNDH_0x2_VBIAS_2 as VBIAS_2,\nBC_CNDH_0x3_VBIAS_3 as VBIAS_3\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as TEMP_0,\nBC_CNDH_0x9_TEMP_1 as TEMP_1,\nBC_CNDH_0xA_TEMP_2 as TEMP_2,\nBC_CNDH_0xB_TEMP_3 as TEMP_3\n-- BC_CNDH_0xC_TEMP_IDPU_0 as TEMP_IDPU\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x8_TEMP_0 as TEMP_0,\nBC_CNDH_0x9_TEMP_1 as TEMP_1,\nBC_CNDH_0xA_TEMP_2 as TEMP_2,\nBC_CNDH_0xB_TEMP_3 as TEMP_3\n-- BC_CNDH_0xC_TEMP_IDPU_0 as TEMP_IDPU\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0xC_TEMP_IDPU_0 as TEMP_IDPU\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0xC_TEMP_IDPU_0 as TEMP_IDPU\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1000) as IBIAS_0,\nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS_1,\nBC_CNDH_0x7_IBIAS_3 / (1000) as IBIAS_3,\nBC_CNDH_0x6_IBIAS_2 / (1000) as IBIAS_2\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1000) as IBIAS_0,\nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS_1,\nBC_CNDH_0x7_IBIAS_3 / (1000) as IBIAS_3,\nBC_CNDH_0x6_IBIAS_2 / (1000) as IBIAS_2\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1000) as IBIAS_0,\nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS_1,\nBC_CNDH_0x6_IBIAS_2 / (1000) as IBIAS_2,\nBC_CNDH_0x7_IBIAS_3 / (1000) as IBIAS_3\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1000) as IBIAS_0,\nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS_1,\nBC_CNDH_0x6_IBIAS_2 / (1000) as IBIAS_2,\nBC_CNDH_0x7_IBIAS_3 / (1000) as IBIAS_3\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as PHOT_CNT_0,\nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT_1,\nBC_CNDH_0x1E_PHOT_CNT_3 as PHOT_CNT_3,\nBC_CNDH_0x1D_PHOT_CNT_2 as PHOT_CNT_2\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as PHOT_CNT_0,\nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT_1,\nBC_CNDH_0x1E_PHOT_CNT_3 as PHOT_CNT_3,\nBC_CNDH_0x1D_PHOT_CNT_2 as PHOT_CNT_2\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as PHOT_CNT_0,\nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT_1,\nBC_CNDH_0x1D_PHOT_CNT_2 as PHOT_CNT_2,\nBC_CNDH_0x1E_PHOT_CNT_3 as PHOT_CNT_3\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as PHOT_CNT_0,\nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT_1,\nBC_CNDH_0x1D_PHOT_CNT_2 as PHOT_CNT_2,\nBC_CNDH_0x1E_PHOT_CNT_3 as PHOT_CNT_3\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1000) as IBIAS_0,\nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS_1,\nBC_CNDH_0x6_IBIAS_2 / (1000) as IBIAS_2,\nBC_CNDH_0x7_IBIAS_3 / (1000) as IBIAS_3\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x4_IBIAS_0 / (1000) as IBIAS_0,\nBC_CNDH_0x5_IBIAS_1 / (1000) as IBIAS_1,\nBC_CNDH_0x6_IBIAS_2 / (1000) as IBIAS_2,\nBC_CNDH_0x7_IBIAS_3 / (1000) as IBIAS_3\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 21 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as PHOT_CNT_0,\nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT_1,\nBC_CNDH_0x1D_PHOT_CNT_2 as PHOT_CNT_2,\nBC_CNDH_0x1E_PHOT_CNT_3 as PHOT_CNT_3\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time, \nBC_CNDH_0x1B_PHOT_CNT_0 as PHOT_CNT_0,\nBC_CNDH_0x1C_PHOT_CNT_1 as PHOT_CNT_1,\nBC_CNDH_0x1D_PHOT_CNT_2 as PHOT_CNT_2,\nBC_CNDH_0x1E_PHOT_CNT_3 as PHOT_CNT_3\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Datastream Enable Mask",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nCBD_DET_0 as CBD_ENA_0,\nIDATA_DET_0 as IDATA_ENA_0,\nCBD_DET_1 as CBD_ENA_1,\nIDATA_DET_1 as IDATA_ENA_1,\nCBD_DET_2 as CBD_ENA_2,\nIDATA_DET_2 as IDATA_ENA_2,\nCBD_DET_3 as CBD_ENA_3,\nIDATA_DET_3 as IDATA_ENA_3\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nCBD_DET_0 as CBD_ENA_0,\nIDATA_DET_0 as IDATA_ENA_0,\nCBD_DET_1 as CBD_ENA_1,\nIDATA_DET_1 as IDATA_ENA_1,\nCBD_DET_2 as CBD_ENA_2,\nIDATA_DET_2 as IDATA_ENA_2,\nCBD_DET_3 as CBD_ENA_3,\nIDATA_DET_3 as IDATA_ENA_3\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Datastream Enable Mask",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 7, "x": 2, "y": 27 },
   "targets": [
    {
     "queryText": "SELECT\nTIME as time,\nCBD_DET_0 as CBD_ENA_0,\nIDATA_DET_0 as IDATA_ENA_0,\nCBD_DET_1 as CBD_ENA_1,\nIDATA_DET_1 as IDATA_ENA_1,\nCBD_DET_2 as CBD_ENA_2,\nIDATA_DET_2 as IDATA_ENA_2,\nCBD_DET_3 as CBD_ENA_3,\nIDATA_DET_3 as IDATA_ENA_3\nfrom fast_ihk",
     "rawQueryText": "SELECT\nTIME as time,\nCBD_DET_0 as CBD_ENA_0,\nIDATA_DET_0 as IDATA_ENA_0,\nCBD_DET_1 as CBD_ENA_1,\nIDATA_DET_1 as IDATA_ENA_1,\nCBD_DET_2 as CBD_ENA_2,\nIDATA_DET_2 as IDATA_ENA_2,\nCBD_DET_3 as CBD_ENA_3,\nIDATA_DET_3 as IDATA_ENA_3\nfrom fast_ihk",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}